/*
 * generated by Xtext
 */
package org.openhab.model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConfigRuntimeModule extends org.openhab.model.AbstractConfigRuntimeModule {

}
