/*
* generated by Xtext
*/
package org.openhab.model.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.openhab.model.sitemap.Group;
import org.openhab.model.sitemap.Sitemap;
import org.openhab.model.sitemap.Switch;
import org.openhab.model.sitemap.Widget;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SitemapLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SitemapLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	String text(Widget widget) {
		String label = widget.getLabel();
		if(label==null) return null;
		return widget.eClass().getName() + " " + label;
	}
	 
    String image(Sitemap sitemap) {
      return "sitemap.png";
    }

    String image(Group group) {
        return "group.png";
      }

    String image(Switch swtch) {
        return "switch.png";
      }

}
