/*
* generated by Xtext
*/
package org.openhab.model.persistence.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class PersistenceOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
