<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sitemap"
    nsURI="http://www.openhab.org/model/Sitemap" nsPrefix="sitemap">
  <eClassifiers xsi:type="ecore:EClass" name="SitemapModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sitemap" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//SitemapModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="item" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkableWidget" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Frame" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//LinkableWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//LinkableWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//LinkableWidget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Image" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//LinkableWidget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Mapping"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slider" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="switchEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappings" upperBound="-1"
        eType="ecore:EClass platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Mapping"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="List" eSuperTypes="platform:/resource/org.openhab.model.sitemap/src-gen/org/openhab/model/Sitemap.ecore#//Widget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapping">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cmd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
