#! /bin/sh
### BEGIN INIT INFO
# Provides: ohpiface
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: ohpiface
# Description: openHAB UDP client/server for PiFace binding
### END INIT INFO

export HOME

. /home/pi/ohpiface.conf

case "$1" in
    start)
        echo "Starting openHAB PiFace UDP client/server (waiting 10s for network to come up)..."
        sleep 10
        /home/pi/ohpiface.py -l $LISTENER_PORT -b $BROADCAST_PORT 2>&1 &
    ;;
    stop)
        echo "Stopping openHAB PiFace UDP client/server"
        PID=`ps auxwww | grep ohpiface.py | head -1 | awk '{print $2}'`
        kill -9 $PID
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
    ;;
esac
exit 0
