/*
* generated by Xtext
*/
package org.openhab.model.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class SitemapTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
