/*
* generated by Xtext
*/
package org.openhab.model.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SitemapOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
