#!/bin/sh

set -e

removeOpenHABInit() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl --no-reload disable openhab.service > /dev/null 2>&1 || :
	else
		update-rc.d openhab remove > /dev/null 2>&1 || :
	fi
}

case "$1" in
	remove)
		removeOpenHABInit
		;;
	purge)
		removeOpenHABInit
		if getent passwd openhab > /dev/null 2>&1; then
			deluser --quiet openhab || true
		fi
		if getent group openhab > /dev/null 2>&1; then
			delgroup --quiet openhab || true
		fi
		rm -rf /var/log/openhab
		rm -rf /var/lib/openhab
		rm -rf /usr/share/openhab/webapps/static
		rm -rf /etc/openhab
		;;
	abort-install|abort-upgrade|disappear|failed-upgrade|upgrade)
		;;
	*)
		echo "postrm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
