#!/bin/sh
if [ "$1" = "remove" ]; then
    /etc/init.d/openhab stop
    update-rc.d -f openhab remove
    installdir="/opt/openhab
    webappdir="${installdir}/webapps/static
    rm -f "${webappdir}/version"
    rm -f "${webappdir}/uuid"
fi
