#!/bin/sh

set -e

[ -f /etc/default/openhab ] && . /etc/default/openhab

stopOpenHAB() {
	if [ -x /bin/systemctl ] ; then
		/bin/systemctl --no-reload stop openhab.service > /dev/null 2>&1 || :
	elif [ -x "/etc/init.d/openhab" ]; then
		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d openhab stop || true
		else
			/etc/init.d/openhab stop || true
		fi
	fi
}

case "$1" in
	upgrade)
		stopOpenHAB
		;;
	remove|deconfigure)
		stopOpenHAB
		;;
	failed-upgrade)
		;;
esac

exit 0
