/**
 * Copyright (c) 2010-2015, openHAB.org and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.persistence.dbms.config.db;

import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Select;
import org.openhab.persistence.dbms.model.ItemVO;
import org.openhab.persistence.dbms.model.ItemsVO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Default Database Configuration class and its inner-classes. Class represents
 * the entire database configuration, it is none specific, but like MySql.
 * 
 * @author Helmut Lehmeyer
 * @since 1.8.0
 */
public class DbmsHsqldb extends DbmsBaseDB {
	private static final Logger logger = LoggerFactory.getLogger(DbmsHsqldb.class);

	public DbmsHsqldb() {
		super();
		initEtendedSqlTypes();
		setDriverClassName("org.hsqldb.jdbcDriver");
	}

	public void initEtendedSqlTypes() {
		// Initialize the type array
		logger.debug("DBMS::initEtendedSqlTypes: Initialize the type array sqlTypes={}", sqlTypes.values());
	}

	@Override
	public int checkMaxConnections(int i) {
		return 1;
	}

	public interface DbDAO extends BaseInnerDAO {
		
		String SQL_PING_DB                         = "SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS";
		String SQL_CREATE_ITEMS_TABLE_IF_NOT       = "CREATE TABLE IF NOT EXISTS ${itemsManageTable} ( ItemId INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL, ${colname} ${coltype} NOT NULL)";
		String SQL_CREATE_NEW_ENTRY_IN_ITEMS_TABLE = "INSERT INTO ${itemsManageTable} (ItemName) VALUES ('${itemname}')";
		String SQL_INSERT_ITEM_VALUE               = "INSERT INTO ${tableName} (TIME, VALUE) VALUES( NOW(), CAST( #{value, javaType=${javaType}, jdbcType=${jdbcType}} as ${dbType}) )";

		@Select(SQL_PING_DB)
		public int doPingDB() throws Exception;

		@Insert(SQL_CREATE_ITEMS_TABLE_IF_NOT)
		public boolean doCreateItemsTableIfNot(ItemsVO vo) throws Exception;

		@Insert(SQL_CREATE_NEW_ENTRY_IN_ITEMS_TABLE)
		@Options(useGeneratedKeys = true, keyProperty = "itemid")
		public int doCreateNewEntryInItemsTable(ItemsVO vo) throws Exception;

		@Insert(SQL_INSERT_ITEM_VALUE)
		public void doInsertItemValue(ItemVO vo) throws Exception;
	}
}
