
/*
 * generated by Xtext
 */
 
package org.openhab.model.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class SitemapExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.openhab.model.ui.internal.SitemapActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.openhab.model.ui.internal.SitemapActivator.getInstance().getInjector("org.openhab.model.Sitemap");
	}
	
}
