/*
* generated by Xtext
*/
package org.openhab.model.persistence.ui.contentassist;

import org.openhab.model.persistence.ui.contentassist.AbstractPersistenceProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PersistenceProposalProvider extends AbstractPersistenceProposalProvider {

}
