package org.openhab

import org.openhab.core.items.Item
import org.openhab.core.library.items.SwitchItem
import org.openhab.core.library.types.OnOffType
import org.openhab.core.types.Command
import org.openhab.io.multimedia.actions.Audio

rule "Standard Doorbell"
	activation-group "doorbell"
	salience -10
	when
		Serial : Item(name=="Doorbell", hasChanged==true, state==OnOffType.ON )
	then
		Audio.playSound("doorbell.wav");
end
