/*
 * generated by Xtext
 */
package org.openhab.model.persistence.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PersistenceUiModule extends org.openhab.model.persistence.ui.AbstractPersistenceUiModule {
	public PersistenceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
