/**
 * Copyright (c) 2010-2014, openHAB.org and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
/*
 * generated by Xtext
 */
package org.openhab.model;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ItemsRuntimeModule extends org.openhab.model.AbstractItemsRuntimeModule {

}
