package org.openhab.binding.nest.internal;

public enum NestType {
	
	NEST_CODE,
	NEST_AUTH_URL,

	THERMOSTAT_CURRENT_TEMP,
	THERMOSTAT_CURRENT_TEMP_F,
	THERMOSTAT_CURRENT_HUMIDITY,
	THERMOSTAT_TARGET_TEMP,
	THERMOSTAT_TARGET_TEMP_F,
	THERMOSTAT_TARGET_HIGH_TEMP,
	THERMOSTAT_TARGET_HIGH_TEMP_F,
	THERMOSTAT_TARGET_LOW_TEMP,
	THERMOSTAT_TARGET_LOW_TEMP_F,
	THERMOSTAT_NAME,
	THERMOSTAT_LONG_NAME,
	THERMOSTAT_LAST_UPDATED,
	THERMOSTAT_HVAC_MODE,
	THERMOSTAT_CAN_HEAT,
	THERMOSTAT_CAN_COOL,
	THERMOSTAT_HAS_FAN,
	THERMOSTAT_IS_ONLINE,
	THERMOSTAT_VERSION,
	
	PROTECT_VERSION,
	PROTECT_NAME,
	PROTECT_LONG_NAME,
	PROTECT_LAST_CONNECTED,
	PROTECT_IS_ONLINE,
	PROTECT_BATTERY_STATE, 
	PROTECT_CO_ALARM_STATE, 
	PROTECT_SMOKE_ALARM_STATE, 
	PROTECT_LAST_MANUAL_TEST,
	PROTECT_UI_COLOUR, 
	
	HOUSE_NAME,
	HOUSE_AWAY_STATE,
	HOUSE_AWAY_STATE_STRING,
	HOUSE_ETA_EARLIEST, 
	HOUSE_ETA_LATEST, 
	;
	
}
