/**
 * Copyright (c) 2010-2016 by the respective copyright holders.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
package org.openhab.binding.intertechno.internal.parser;

import java.util.List;

import org.openhab.model.item.binding.BindingConfigParseException;

/**
 * All parsers for Intertechno configs need to implement this interface.
 *
 * @author Till Klocke
 * @since 1.4.0
 */
public interface IntertechnoAddressParser {

    /**
     * Parse the config from the given config parts. After this method was called
     * the on and off commands can be read with getCommand(ON|OFF).
     * 
     * @param addressParts
     *            String list, which contains config items like this:
     *            <name>=<value>.
     * @throws BindingConfigParseException
     */
    public void parseConfig(List<String> configParts) throws BindingConfigParseException;

    /**
     * Returns the ON command, generated by the concrete parser.
     * 
     * @return The ON command
     */
    public String getCommandON();

    /**
     * Returns the OFF command, generated by the concrete parser.
     * 
     * @return The OFF command.
     */
    public String getCommandOFF();

}
