/**
 * Copyright (c) 2010-2014, openHAB.org and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 */
/*
 * generated by Xtext
 */
package org.openhab.model.persistence;

import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.openhab.model.persistence.scoping.PersistenceGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PersistenceRuntimeModule extends org.openhab.model.persistence.AbstractPersistenceRuntimeModule {

	@Override
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return PersistenceGlobalScopeProvider.class;
	}
}
